replicaCount: 1

image:
  repository: quay.io/ennlight103/hello-world  #replace with your image repository
  pullPolicy: IfNotPresent
  tag: "latest"  # defaults to the chart version

service:
  type: ClusterIP
  port: 8080